# Generated by Django 4.2.3 on 2023-07-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='level',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermidiate'), ('3', 'Advansed')], default='1', max_length=20),
        ),
    ]
