# Generated by Django 4.2.3 on 2023-07-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_teacher_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='decription',
            field=models.TextField(blank=True),
        ),
    ]
