# Generated by Django 4.2.3 on 2023-07-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_path_teacher_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Path',
        ),
    ]
