# Generated by Django 4.2.3 on 2023-07-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_section', models.CharField(max_length=128)),
                ('number_of_videos', models.IntegerField()),
                ('time_of_videos', models.IntegerField()),
                ('number_of_readings', models.IntegerField()),
                ('time_of_readings', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('number_of_quizes', models.IntegerField()),
                ('number_of_assignments', models.IntegerField()),
                ('teacher_username', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.teacher')),
            ],
        ),
    ]
