# Generated by Django 4.2.3 on 2023-07-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='section',
        ),
    ]
