# Generated by Django 4.2.3 on 2023-07-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=128)),
                ('content_time', models.IntegerField()),
                ('content_type', models.CharField(choices=[('1', 'Reading'), ('2', 'Video'), ('3', 'Quiz'), ('4', 'Assignment')], max_length=20)),
                ('teacher_username', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.teacher')),
            ],
        ),
    ]
