# Generated by Django 4.2.3 on 2023-07-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.TextField()),
                ('content_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.content')),
            ],
        ),
    ]
