# Generated by Django 4.2.3 on 2023-07-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_readingcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_of_content', models.IntegerField()),
                ('content_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.content')),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.section')),
            ],
        ),
    ]
