# Generated by Django 4.2.3 on 2023-07-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
