# Generated by Django 4.2.3 on 2023-07-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectioncontent',
            unique_together={('section_name', 'content_name')},
        ),
        migrations.CreateModel(
            name='TagSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.section')),
                ('tage_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.tag')),
            ],
        ),
    ]
