# Generated by Django 4.2.3 on 2023-07-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_sectioncontent_unique_together_tagsection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagsection',
            unique_together={('section_name', 'tage_name')},
        ),
    ]
