# Generated by Django 4.2.3 on 2023-07-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_tagsection_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_of_section', models.IntegerField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.section')),
            ],
            options={
                'unique_together': {('course_name', 'section_name')},
            },
        ),
    ]
