# Generated by Django 4.2.3 on 2023-07-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
