# Generated by Django 4.2.3 on 2023-07-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
    ]
