# Generated by Django 4.2.3 on 2023-07-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='y',
            field=models.IntegerField(blank=True),
        ),
    ]
