# Generated by Django 4.2.2 on 2023-07-28 19:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0027_alter_blog_options_blog_is_published_blog_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manger',
            new_name='Company',
        ),
    ]
