# Generated by Django 4.2.2 on 2023-07-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_rename_manger_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='decription',
            field=models.TextField(),
        ),
    ]
