# Generated by Django 4.2.2 on 2023-07-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_obada_alter_teacher_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obada',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
