# Generated by Django 4.2.2 on 2023-07-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_alter_applicationform_contact_person_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='estimated_number_of_course_programes_plan_to_create',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
